<a href="https://colab.research.google.com/github/Danny-Dasilva/linalg/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([100, 20, 30, 40, 50])

Array dimensions






In [4]:
a.shape

(5,)

In [6]:
A = np.array([[3, 3, 3], 
              [4, 4, 4],
              [5, 5, 5]])

In [8]:
A.shape

(3, 3)

Pulling a submatrix

In [13]:
B = A[1:2]

In [14]:
B

array([[4, 4, 4]])

Special Matrices

In [17]:
I = np.eye(3)

In [18]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((6, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.full((4, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
X = np.random.random((2000,2))
X

array([[0.1994887 , 0.36911355],
       [0.76221234, 0.70940047],
       [0.07891759, 0.71977367],
       ...,
       [0.23711553, 0.21917329],
       [0.69908414, 0.18267961],
       [0.30755806, 0.22313901]])

Calculations


In [45]:
np.mean(X)

0.5014596328839194

Standard deviation
$$Var(X) = E(X^2) - E^2(X) = \int_{0}^1 x^2 \ dx - \frac{1}{4} = \frac{1}{3} - \frac{1}{4} = \frac{1}{12}$$

In [46]:
np.std(X)**2

0.08337017331449782

In [47]:
1/12

0.08333333333333333

Typing

In [48]:
X.dtype

dtype('float64')

Matrix addition Subtraction


In [64]:
A = np.array([[11, 15, 6],
              [13, 4, 5],
              [6, 15, 13]])
B = np.array([[4, 8, 1],
              [1, 6, 3],
              [2, 7, 1]])
print(A)
print(B)

[[11 15  6]
 [13  4  5]
 [ 6 15 13]]
[[4 8 1]
 [1 6 3]
 [2 7 1]]


In [65]:
C = A+B
C

array([[15, 23,  7],
       [14, 10,  8],
       [ 8, 22, 14]])

In [66]:
np.add(A, B) # dtype as optional param

array([[15, 23,  7],
       [14, 10,  8],
       [ 8, 22, 14]])

In [67]:
C = A-B
C

array([[ 7,  7,  5],
       [12, -2,  2],
       [ 4,  8, 12]])

In [68]:
np.subtract(A, B)

array([[ 7,  7,  5],
       [12, -2,  2],
       [ 4,  8, 12]])

Matrix Multiplication (pointwise multiplication)
and Matrix Division



In [69]:
C = A*B
C

array([[ 44, 120,   6],
       [ 13,  24,  15],
       [ 12, 105,  13]])

In [70]:
np.multiply(A, B)

array([[ 44, 120,   6],
       [ 13,  24,  15],
       [ 12, 105,  13]])

In [72]:
C = A/B
C

array([[ 2.75      ,  1.875     ,  6.        ],
       [13.        ,  0.66666667,  1.66666667],
       [ 3.        ,  2.14285714, 13.        ]])

In [73]:
np.divide(A, B)

array([[ 2.75      ,  1.875     ,  6.        ],
       [13.        ,  0.66666667,  1.66666667],
       [ 3.        ,  2.14285714, 13.        ]])

# Matrix Products

In [76]:
np.matmul(A, B)

array([[ 71, 220,  62],
       [ 66, 163,  30],
       [ 65, 229,  64]])

$$C = AB$$

$$C_{ij} = \sum_{k=1}^N A_{ik}B_{kj}$$

In [78]:
np.dot(A, B)

array([[ 71, 220,  62],
       [ 66, 163,  30],
       [ 65, 229,  64]])

$$<A,B> = A^T B = \sum_{i=1}^n A_i B_i$$

In [ ]:
transpose