<a href="https://colab.research.google.com/github/Danny-Dasilva/linalg/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([100, 20, 30, 40, 50])

Array dimensions






In [4]:
a.shape

(5,)

In [6]:
A = np.array([[3, 3, 3], 
              [4, 4, 4],
              [5, 5, 5]])

In [8]:
A.shape

(3, 3)

Pulling a submatrix

In [13]:
B = A[1:2]

In [14]:
B

array([[4, 4, 4]])

Special Matrices

In [17]:
I = np.eye(3)

In [18]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((6, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.full((4, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
X = np.random.random((2000,2))
X

array([[0.1994887 , 0.36911355],
       [0.76221234, 0.70940047],
       [0.07891759, 0.71977367],
       ...,
       [0.23711553, 0.21917329],
       [0.69908414, 0.18267961],
       [0.30755806, 0.22313901]])

Calculations


In [45]:
np.mean(X)

0.5014596328839194

Standard deviation
$$Var(X) = E(X^2) - E^2(X) = \int_{0}^1 x^2 \ dx - \frac{1}{4} = \frac{1}{3} - \frac{1}{4} = \frac{1}{12}$$

In [46]:
np.std(X)**2

0.08337017331449782

In [47]:
1/12

0.08333333333333333

Typing

In [48]:
X.dtype

dtype('float64')

Matrix addition Subtraction


In [25]:
A = np.array([[1, 5, 6],
              [1, 8, 9],
              [0, -1, 6]])
B = np.array([[4, 8, 1],
              [1, 6, 3],
              [2, 7, 1]])
print(A)
print(B)

[[ 1  5  6]
 [ 1  8  9]
 [ 0 -1  6]]
[[4 8 1]
 [1 6 3]
 [2 7 1]]


In [4]:
C = A+B
C

array([[15, 23,  7],
       [14, 10,  8],
       [ 8, 22, 14]])

In [5]:
np.add(A, B) # dtype as optional param

array([[15, 23,  7],
       [14, 10,  8],
       [ 8, 22, 14]])

In [6]:
C = A-B
C

array([[ 7,  7,  5],
       [12, -2,  2],
       [ 4,  8, 12]])

In [7]:
np.subtract(A, B)

array([[ 7,  7,  5],
       [12, -2,  2],
       [ 4,  8, 12]])

Matrix Multiplication (pointwise multiplication)
and Matrix Division



In [8]:
C = A*B
C

array([[ 44, 120,   6],
       [ 13,  24,  15],
       [ 12, 105,  13]])

In [9]:
np.multiply(A, B)

array([[ 44, 120,   6],
       [ 13,  24,  15],
       [ 12, 105,  13]])

In [10]:
C = A/B
C

array([[ 2.75      ,  1.875     ,  6.        ],
       [13.        ,  0.66666667,  1.66666667],
       [ 3.        ,  2.14285714, 13.        ]])

In [11]:
np.divide(A, B)

array([[ 2.75      ,  1.875     ,  6.        ],
       [13.        ,  0.66666667,  1.66666667],
       [ 3.        ,  2.14285714, 13.        ]])

# Matrix Products

In [12]:
np.matmul(A, B)

array([[ 71, 220,  62],
       [ 66, 163,  30],
       [ 65, 229,  64]])

$$C = AB$$

$$C_{ij} = \sum_{k=1}^N A_{ik}B_{kj}$$

In [78]:
np.dot(A, B)

array([[ 71, 220,  62],
       [ 66, 163,  30],
       [ 65, 229,  64]])

$$<A,B> = A^T B = \sum_{i=1}^n A_i B_i$$

In [13]:
np.inner(A,B)

array([[170, 119, 133],
       [ 89,  52,  59],
       [157, 135, 130]])

In [15]:
np.tensordot(A,B, axes=([1,0], [0,1]))

array(298)

In [16]:
np.linalg.matrix_power(A, 1)

array([[11, 15,  6],
       [13,  4,  5],
       [ 6, 15, 13]])

$$C = A \odot B $$

In [18]:
np.kron (A,B)

array([[ 44,  88,  11,  60, 120,  15,  24,  48,   6],
       [ 11,  66,  33,  15,  90,  45,   6,  36,  18],
       [ 22,  77,  11,  30, 105,  15,  12,  42,   6],
       [ 52, 104,  13,  16,  32,   4,  20,  40,   5],
       [ 13,  78,  39,   4,  24,  12,   5,  30,  15],
       [ 26,  91,  13,   8,  28,   4,  10,  35,   5],
       [ 24,  48,   6,  60, 120,  15,  52, 104,  13],
       [  6,  36,  18,  15,  90,  45,  13,  78,  39],
       [ 12,  42,   6,  30, 105,  15,  26,  91,  13]])

#Matrix Decompositions


Cholesky Decomposition $$A = UU^U$$

In [29]:
U = np.linalg.cholesky(A)
U

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  2.64575131,  0.        ],
       [ 0.        , -0.37796447,  2.42015348]])

In [30]:
np.matmul(U, U.transpose().conj())

array([[ 1.,  1.,  0.],
       [ 1.,  8., -1.],
       [ 0., -1.,  6.]])

In [32]:
D = np.array(([1, -2j], [2j, 5]))

In [34]:
D

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [37]:
U = np.linalg.cholesky(D)
U

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [38]:
np.matmul(U, U.T.conj())

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

QR decomposition $$A= QR$$

In [39]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [43]:
Q = np.linalg.qr(A)[0]
R = np.linalg.qr(A)[1]


In [44]:
np.matmul(Q,R)

array([[ 1.,  5.,  6.],
       [ 1.,  8.,  9.],
       [ 0., -1.,  6.]])

EigenValue Decomposition (EVD) $$A = PDP^{-1}$$

In [47]:
(d,P) = np.linalg.eig(A)
print(d, P)
D = np.diag(d)
print(D)

[0.34454138+0.j         7.32772931+2.69350537j 7.32772931-2.69350537j] [[ 0.9940235 +0.j          0.52656174+0.00429702j  0.52656174-0.00429702j]
 [-0.10749871+0.j          0.80658014+0.j          0.80658014-0.j        ]
 [-0.01900796+0.j         -0.11875577+0.24091455j -0.11875577-0.24091455j]]
[[0.34454138+0.j         0.        +0.j         0.        +0.j        ]
 [0.        +0.j         7.32772931+2.69350537j 0.        +0.j        ]
 [0.        +0.j         0.        +0.j         7.32772931-2.69350537j]]


In [49]:
np.real(np.matmul(np.matmul(P,D), np.linalg.inv(P)))

array([[ 1.00000000e+00,  5.00000000e+00,  6.00000000e+00],
       [ 1.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [-5.55111512e-17, -1.00000000e+00,  6.00000000e+00]])

In [50]:
np.linalg.eigvals(A)

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

Singular Valued Decomposition (SVD) $$A = U S V^T $$

In [52]:
(U,s,V) = np.linalg.svd(A)
print(U, s, V)

[[ 0.52419682 -0.12063215  0.84300983]
 [ 0.80286468 -0.26006138 -0.53644792]
 [ 0.28394717  0.95802712 -0.03947205]] [14.9764806   4.53978289  0.30886909] [[ 0.0886097   0.58491408  0.80624056]
 [-0.08385721 -0.80217028  0.59117747]
 [ 0.99253025 -0.11999315 -0.02203081]]


# Matrix Norms


In [53]:
np.linalg.norm(A)

15.652475842498529

In [54]:
np.linalg.cond(A)

48.48811774406207

In [55]:
np.linalg.det(A)

21.0

In [56]:
np.linalg.matrix_rank(A)

3

In [57]:
np.trace(A)

15

# Solving Equations

$$ Ax = b $$

In [58]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [59]:
b = np.random.random((3,1))
b

array([[0.54008772],
       [0.95554526],
       [0.46385869]])

In [61]:
x1 = np.matmul(np.linalg.inv(A), b)
x1

array([[-0.23839073],
       [ 0.05243663],
       [ 0.08604922]])

In [62]:
x2 = np.linalg.solve(A,b)
x2

array([[-0.23839073],
       [ 0.05243663],
       [ 0.08604922]])

In [64]:
S = np.array([[1,2], [2,4]])
S

array([[1, 2],
       [2, 4]])

In [67]:
np.matmul(np.linalg.pinv(S),S)

array([[0.2, 0.4],
       [0.4, 0.8]])